### ISSUE TITLE
请问 v-finger:swipe 如何传自定义参数？

### ISSUE THREAD

**Issue by csdudu** [shhdgit/vue-finger#1]
比如：
v-finger:swipe="swipeH( id , $event )"  这样使用可行？
我现在这样用就报错。如果不行，可有什么变通办法？

**Comment by shhdgit** [comment]
@csdudu 试试写成: v-finger:swipe="swipeH( $event, id )"
methods中定义siwpeH: function (evt, id) {}

**Comment by csdudu** [comment]
按您说的这样写了，报错：
![image](https://cloud.githubusercontent.com/assets/5706088/26290369/93c29efa-3ed9-11e7-91a5-bf2b79de5fa1.png)

但是id还是传送过去了。

**Comment by shhdgit** [comment]
https://github.com/AlloyTeam/AlloyFinger/blob/master/vue/example/vue2/test.html
参考这里press-move的写法吧
